config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#home'

  devise_for :users

  resources :homes, only: [:index]

  resources :workouts do
    resources :exercises, except: [:index, :show]
  end

  namespace :trainer do
    resources :users, only: [:index, :show]
  end

  resources :sendworkout, only: [:new, :create]

  resources :completeds, only: [:index, :create]
end

app/models/completed.rb
class Completed < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout

  validates :user, presence: true
  validates :workout, presence: true
  validates :workout_name, presence: true

  def self.last_30_days_for(user)
    where('user_id = ? and created_at > ?', user, 30.days.ago)
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout

  validates :activity, presence: true, length: { in: 5..50 }
  validates :intensity, presence: true, length: { in: 2..50 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :workouts
  has_many :completeds

  validates :fullname, presence: true
  validates :fullname, length: { in: 3..30 }
  validates :fullname, uniqueness: true

  def trainer?
    role == 'trainer'
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  has_many :exercises, dependent: :destroy
  has_many :completeds

  validates :name, presence: true, length: { in: 4..50 }
  validates :description, presence: true, length: { in: 15..250 }
  validates :user, presence: true

  def visible_table?
    if exercises.any?
      ''
    else
      'hide'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def authorize_trainer!
    if current_user.nil? || !current_user.trainer?
      flash[:notice] = "Must be a trainer to view this page"
      redirect_to workouts_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :fullname
    devise_parameter_sanitizer.for(:account_update) << :fullname
  end
end

app/controllers/completeds_controller.rb
class CompletedsController < ApplicationController
  before_action :authenticate_user!

  def index
    @completeds = Completed.last_30_days_for(current_user)
    @workouts_for_bar = @completeds.count
    @non_workouts = 30 - @workouts_for_bar
    @percent_done = (@workouts_for_bar * 100) / 30
  end

  def create
    @workout_id = Workout.find_by(id: params[:workout_id])
    @workout_name = params[:workout_name]
    @completed = Completed.new(
      workout: @workout_id,
      workout_name: @workout_name,
      user: current_user
    )
    if @completed.save
      flash[:success] = "Great job completing your workout!"
      redirect_to completeds_path
    else
      flash[:notice] = @completed.errors.full_messages.join(". ")
      render :new
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
    if current_user
      redirect_to workouts_path
    else
      redirect_to homes_path
    end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!

  def create
    not_user_redirect
    @workout = Workout.find(params[:workout_id])
    @exercise = Exercise.new(exercise_params)
    @exercise.workout = @workout
    respond_to do |format|
      if @exercise.save
        format.json { render json: @exercise }
      else
        format.json { render json: @exercise.errors.full_messages.join(". ") }
      end
    end
  end

  def edit
    not_user_redirect
    @exercise = Exercise.find(params[:id])
  end

  def update
    not_user_redirect
    @exercise = Exercise.find(params[:id])
    if @exercise.update_attributes(exercise_params)
      flash[:success] = 'Your exercise has been updated'
      redirect_to workout_path(@exercise.workout)
    else
      flash[:notice] = @exercise.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id]).destroy
    flash[:success] = "Your exercise has been taken out of your workout"
    redirect_to edit_workout_path(params[:workout_id])
  end

  def not_user_redirect
    user = Workout.find(params[:workout_id]).user
    if user != current_user && current_user.role != 'trainer'
      flash[:notice] = "Only workouts you created are viewable and/or editable"
      redirect_to workouts_path
    end
  end

  private

  def exercise_params
    if params['exercise']
      params.require(:exercise).permit(:workout_id, :activity, :intensity)
    else
      param_hash = JSON.parse(params.keys[0])
      param_hash[:workout_id] = params[:workout_id]
      param_hash
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/sendworkout_controller.rb
class SendworkoutController < ApplicationController
  def new
    @workout = Workout.new
    @users = User.all.map { |user| [user.fullname, user.id] }
  end
end

app/controllers/trainer/users_controller.rb
class Trainer::UsersController < ApplicationController
  before_action :authorize_trainer!

  def index
    @users = User.all.order(:fullname).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @workouts = Workout.where(user: @user).page(params[:page]).per(10)
    @completeds = Completed.last_30_days_for(@user)
    @workouts_for_bar = @completeds.count
    @non_workouts = 30 - @workouts_for_bar
    @percent_done = (@workouts_for_bar * 100) / 30
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!

  def index
    @workouts = current_user.workouts
  end

  def show
    @workout = Workout.find(params[:id])
    not_user_redirect
    @exercises = Exercise.where(workout: params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user ||= current_user
    if @workout.save
      if current_user.role = "trainer"
        WorkoutMailer.new_workout(@workout).deliver_later
      end
      flash[:success] = "Workout created! Add some excercises!"
      redirect_to edit_workout_path(@workout)
    else
      flash[:notice] = @workout.errors.full_messages.join(". ")
      if @workout.user == current_user
        render :new
      else
        @users = User.all.map { |user| [user.fullname, user.id] }
        render 'sendworkout/new'
      end
    end
  end

  def edit
    @workout = Workout.find(params[:id])
    not_user_redirect
    @exercise = Exercise.new
  end

  def update
    @workout = Workout.find(params[:id])
    not_user_redirect
    if @workout.update_attributes(workout_params)
      flash[:success] = 'Changes saved successfully'
      redirect_to edit_workout_path(@workout)
    else
      flash[:notice] = @workout.errors.full_messages.join(". ")
      @exercise = Exercise.new
      @exercises = @workout.exercises
      render :edit
    end
  end

  def destroy
    @workout = Workout.find(params[:id]).destroy
    flash[:success] = "Deleted"
    redirect_to workouts_path
  end

  def not_user_redirect
    if @workout.user != current_user && current_user.role != 'trainer'
      flash[:notice] = "Only workouts you created are viewable and/or editable"
      redirect_to workouts_path
    end
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :description, :user, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def will_show_nav_items_for?(action, controller)
    params[:action] == action && params[:controller] == controller
  end

  def class_active(action, controller)
    if params[:action] == action && params[:controller] == controller
      'active '
    end
  end
end

app/helpers/my_custom_helper.rb
module MyCustomHelper
  def will_show_nav_items_for?(action, controller)
    params[:action] == action && params[:controller] == controller
  end

  def class_active(action, controller)
    if params[:action] == action && params[:controller] == controller
      'active '
    end
  end
end

app/views/completeds/index.html.erb
<div class='padding-fifteen'>
  <h1>Completed Workouts</h1>
  <div class='status-container full-width'>
    <% if @workouts_for_bar <= 25 %>
      <% @workouts_for_bar.times do %>
        <div class="workout-status status-boxes"></div>
      <% end %>
      <div class="non-workout-status status-boxes status-index">
        <%= @percent_done %>%
      </div>
      <% (@non_workouts - 1).times do %>
        <div class="non-workout-status status-boxes"></div>
      <% end %>
    <% else %>
      <div class="workout-status status-boxes status-index">
        <%= @percent_done %>%
      </div>
      <% (@workouts_for_bar-1).times do %>
        <div class="workout-status status-boxes"></div>
      <% end %>
      <% unless @non_workouts == 0 %>
        <% @non_workouts.times do %>
          <div class="non-workout-status status-boxes"></div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <br />
  <% if @completeds.empty? %>
    <p>You have not completed any workouts in the last 30 days. <%= link_to "Click here", new_workout_path %>
      to pick a workout to complete!</p>
  <% else %>
  (last 30 days only)
    <table class="full-width">
      <thead>
        <tr>
          <th>Workout</th>
          <th>Date completed</th>
        </tr>
      </thead>
      <% @completeds.each do |completed| %>
        <tr>
          <% if Workout.where(id: completed.workout_id).empty? %>
            <td><%= completed.workout_name %></td>
          <% else %>
            <td><%= link_to completed.workout_name, workout_path(completed.workout_id) %></td>
          <% end %>
          <td><%= completed.created_at.strftime("%b %d") %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/exercises/edit.html.erb
<h4>Edit:</h4>
<div class="row">
  <div class="medium-8 medium-offset-2 custom-container container">
    <%= form_for [ @exercise.workout, @exercise ] do |f| %>
      <%= f.label "activity" %>
      <%= f.text_field :activity %>

      <%= f.label "intensity" %>
      <%= f.text_field :intensity %>

      <%= f.submit "Update Exercise", class: "button tiny round" %>
    <% end %>
  </div>
</div>

app/views/homes/index.html.erb
Login to start using WorkoutPartner!

app/views/layouts/_flash.html.erb
<div id="notice_wrapper">
  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <p class="notice"><%= value %></p>
    </div>
  <%- end -%>
</div>

app/views/layouts/_not_small_nav_bar.html.erb
<nav id="menu" role="navigation" class="hide-for-small top-bar">
  <section class="top-bar-section title-area">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to "Workout List", workouts_path %></li>
        <% if current_user.role == 'trainer' %>
          <li><%= link_to "Completed", completeds_path %></li>
          <li><%= link_to "Create New", new_sendworkout_path %></li>
        <% else %>
          <li><%= link_to "Create New", new_workout_path %></li>
          <li><%= link_to "Completed", completeds_path %></li>
        <% end %>
        <% if current_user.role == 'trainer' %>
          <li><%= link_to "User List", trainer_users_path %></li>
        <% end %>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      </ul>
      <ul>
        <dl class="tabs five-up hide-for-small sign-in nav-bottom">
          <% if will_show_nav_items_for?("show", "workouts") || will_show_nav_items_for?("edit", "workouts") || will_show_nav_items_for?("new", "exercises")%>
              <dd class=<%= class_active("show", "workouts") %>><%= link_to "Details", workout_path(@workout) %></dd>
              <dd class=<%= class_active("edit", "workouts") %>><%= link_to "Edit", edit_workout_path(@workout) %></dd>
              <dd><%= link_to 'Delete',  workout_path(@workout),  method: :delete, data: { confirm: 'Are you sure you want to delete this workout?' } %></dd>
            <% end %>
        </dl>
      </ul>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>
<div class="row">
</div>

app/views/layouts/_small_nav_bar.html.erb
<% if current_user %>
  <nav class="tab-bar sticky show-for-small-only">
    <section class="tab-bar-section add-padding">
      <% if current_user.role != 'trainer' %>
        <%= link_to "Workouts", workouts_path %>
        <%= link_to "Completed", completeds_path %>
        <%= link_to "Create", new_workout_path %>
      <% else %>
        <%= link_to "User list", trainer_users_path %>
        <%= link_to "Create New Workout", new_sendworkout_path %>
      <% end %>
    </section>
    <section class="right-small">
      <a class="right-off-canvas-toggle menu-icon" href="#"><span></span></a>
    </section>
  </nav>

  <aside class="right-off-canvas-menu show-for-small-only">
    <ul class="off-canvas-list">
      <li><label> Welcome! </label></li>
      <%- if current_user %>
        <% if current_user.role == 'trainer' %>
          <li><%= link_to "Your Workouts", workouts_path %></li>
          <li><%= link_to "Completed", completeds_path %></li>
        <% end %>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </aside>
<% else %>
<nav class="tab-bar sticky show-for-small-only">
  <section class="tab-bar-section add-padding">
    <%= link_to 'Sign Up', new_user_registration_path %>
    <%= link_to 'Sign In', new_user_session_path %>
  </section>
</nav>
<% end %>

<dl class="tabs five-up show-for-small nav-bottom">
  <% if will_show_nav_items_for?("show", "workouts") || will_show_nav_items_for?("edit", "workouts") || will_show_nav_items_for?("new", "exercises")%>
    <dd class=<%= class_active("show", "workouts") %>>
      <%= link_to fa_icon("eye"),  workout_path(@workout) %>
    </dd>
    <dd class=<%= class_active("edit", "workouts") %>>
      <%= link_to fa_icon("pencil"),  edit_workout_path(@workout) %>
    </dd>
    <dd>
      <%= link_to fa_icon("trash-o"),  workout_path(@workout),  method: :delete, data: { confirm: 'Are you sure you want to delete this workout?' } %>
    </dd>
  <% end %>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width" />
  <title class="title-area">WorkoutPartner</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>

</head>
<body id="grad">
  <div class="main-title">
    <h1>
      <a href='<%= workouts_path %>'>
        <span class="fa-stack">
          <i class="fa fa-star fa-stack-2x orange"></i>
          <i class="fa fa-check fa-stack-1x"></i>
        </span>
        WorkoutPartner</a>
    </h1>
  </div>
  <%= render "layouts/flash" %>

  <div class="off-canvas-wrap fixed" data-offcanvas>
    <div class="inner-wrap">

      <%= render "layouts/small_nav_bar.html" %>
      <%= render "layouts/not_small_nav_bar.html" %>

      <section class="main-section">
        <div class="row fullWidth">
          <div class="small-12 small-centered text-center">
            <div class="row">
              <div class="medium-8 medium-offset-2 custom-container container has-table">
              <%= yield %>
              </div>
            </div>
          </div>
      </section>
        <a class="exit-off-canvas"></a>
        </div>
    </div>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>

app/views/sendworkout/new.html.erb
<div class='padding-fifteen'>
  <%= form_for @workout do |f| %>
    <%= f.label 'Create workout for' %>
    <%= f.select :user_id, options_for_select(@users) %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.submit "Create Workout", class: "button tiny round" %>
  <% end %>
</div>

app/views/trainer/users/index.html.erb
<div class='padding-fifteen'>
  <h1>Users</h1>
  <% if @users.empty? %>
    No users in durrent database.
  <% else %>
    <table class="full-width word-wrap">
      <thead>
        <tr>
          <th>Name</th>
          <th class="hide-for-small">Email</th>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to "#{user.fullname}", trainer_user_path(user) %></td>
          <td th class="hide-for-small"><%= user.email %></td>
        </tr>
      <% end %>
    </table>
    <%= paginate @users %>
  <% end %>
</div>

app/views/trainer/users/show.html.erb
<div class="row">
  <div class="medium-8 medium-offset-2 custom-container container">
    <h1><%= @user.fullname %></h1>
    <p class='break-word'><%= @user.email %></p>
  </div>
</div>


<h3>Completed Workouts</h3>
<div class='status-container full-width'>
  <% if @workouts_for_bar <= 25 %>
    <% @workouts_for_bar.times do %>
      <div class="workout-status status-boxes"></div>
    <% end %>
    <div class="non-workout-status status-boxes status-index">
      <%= @percent_done %>%
    </div>
    <% @non_workouts.times do %>
      <div class="non-workout-status status-boxes"></div>
    <% end %>
  <% else %>
    <div class="workout-status status-boxes status-index">
      <%= @percent_done %>%
    </div>
    <% (@workouts_for_bar-1).times do %>
      <div class="workout-status status-boxes"></div>
    <% end %>
    <% unless @non_workouts == 0 %>
      <% @non_workouts.times do %>
        <div class="non-workout-status status-boxes"></div>
      <% end %>
    <% end %>
  <% end %>
</div>
<br />
<div class="row">
  <div class="medium-8 medium-offset-2 custom-container container">
    <% if @completeds.empty? %>
        <p>
          <%= @user.fullname %> has not completed any workouts in the last 30 days.
        </p>

    <% else %>
      <table class="full-width">
        <thead>
          <tr>
            <th>Workout</th>
            <th>Date completed</th>
          </tr>
        </thead>
        <% @completeds.each do |completed| %>
          <tr>
            <% if Workout.where(id: completed.workout_id).empty? %>
              <td><%= completed.workout_name %></td>
            <% else %>
              <td><%= link_to completed.workout_name, workout_path(completed.workout_id) %></td>
            <% end %>
            <td><%= completed.created_at.strftime("%b %d") %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

<h3>All Workouts</h3>
<% if @workouts.empty? %>
  <div class="row">
    <div class="medium-8 medium-offset-2 custom-container container">
      <p>
        This user does not have any workouts.
      </p>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="medium-8 medium-offset-2 custom-container container">
      <table  class="full-width">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
          </tr>
        </thead>
        <% @workouts.each do |workout| %>
          <tr>
            <td>
              <div><%= link_to "#{workout.name}", workout_path(workout) %></div>
            </td>
            <td>
              <div><%= workout.description %></div>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<%= paginate @workouts %>
<% end %>

app/views/workouts/edit.html.erb
<div class="row">
  <div class="medium-8 medium-offset-2 custom-container container">
  <h4>Edit Workout Info
  <% if current_user.role == 'trainer' %>
    for <%= @workout.user.fullname %>
  <% end %>
  :</h4>
  <%= form_for @workout do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.submit "Submit Changes", class: "button tiny round" %>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="medium-8 medium-offset-2 custom-container container">
  </div>
</div>


<div class="row">
  <div class="medium-8 medium-offset-2 custom-container container">
    <h4>Exercises for <%= @workout.name %></h4>
    <table class="full-width exercises-table-edit-page <%= @workout.visible_table? %>" id="" style="table-layout:fixed;">
      <thead>
        <tr>
          <th class="width-icons"></th>
          <th class="width-icons"></th>
          <th><Activity>Exercises</Activity></th>
        </tr>
      </thead>
      <tbody class='exercises-table-list'>
        <% unless @workout.exercises.empty? %>
          <% @workout.exercises.each do |exercise| %>
            <tr>
              <td class="icon-edit width-icons">
                <%= link_to fa_icon("pencil"), edit_workout_exercise_path(@workout, exercise), class: "edit-icon" %>
              </td>
              <td class="icon-edit delete-icon-td width-icons">
                <%= link_to  fa_icon("times"),  workout_exercise_path(@workout, exercise),  method: :delete, class: 'delete-icon', data: { confirm: 'Are you sure you want to delete this exercise?' } %>
              </td>
              <td>
                <div class="exercise-type"><%= exercise.activity %></div>
                <div class="exercise-intensity"><%= exercise.intensity %></div>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>



<div class="row">
  <div class="medium-8 medium-offset-2 custom-container container">
    <p>Add to your workout by following this example:</p>
    <table class="example-table full-width" style="table-layout:fixed;">
      <thead>
        <tr>
          <th>Activity</th>
          <th>Intensity</th>
        </tr>
      </thead>
      <tr>
        <td>30 seconds of planking</td>
        <td>4 times with 30 second breaks</td>
      </tr>
    </table>
    <div class="new-exercise container" id="new-exercise">
      <%= form_for [ @workout, @exercise ] do |f| %>
        <%= f.label "Activity" %>
        <%= f.text_field :activity %>

        <%= f.label "Intensity" %>
        <%= f.text_field :intensity %>

        <%= f.submit "Add to workout", class: "button tiny round submit-new-exercise" %>
      <% end %>
    </div>
  </div>
</div>

app/views/workouts/index.html.erb
<div class="padding-fifteen">
  <h1>Your Workouts</h1>
  <% if @workouts.empty? %>
    You have no workouts. <%= link_to "Click here", new_workout_path %> to create one!
  <% else %>
  <div>
    <table class="full-width" style="table-layout:fixed;">
      <thead>
        <tr>
          <th class="hide-for-small width-icons"></th>
          <th>Workout</th>
          <th>Description</th>
        </tr>
      </thead>
      <% @workouts.each do |workout| %>
        <tr>
          <td class="hide-for-small icon-edit width-icons"><%= link_to fa_icon('trash'),  workout_path(workout),  method: :delete, data: { confirm: 'Are you sure you want to delete this workout?' } %></td>
          <td><%= link_to "#{workout.name}", workout_path(workout) %></td>
          <td class="break-word"><%= truncate("#{workout.description}", length: 50, separator: ' ') %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <% end %>
</div>

app/views/workouts/new.html.erb
  <%= form_for @workout do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.submit "Create Workout", class: "button tiny round" %>
  <% end %>

app/views/workouts/show.html.erb
<div class="row">
  <div class="medium-8 medium-offset-2 custom-container container">
    <h1><%= @workout.name %></h1>
    <% if current_user.role == 'trainer' %>
      <p>Workout for: <%= @workout.user.fullname %></p>
    <% end %>
    <p><%= @workout.description %></p>
  </div>
</div>

<% if @exercises.empty? %>
  <div class="row">
    <div class="medium-8 medium-offset-2 custom-container container">
      <p>
        You do not have any exercises for this workout. Add exercises
        <%= link_to "here!", edit_workout_path(@workout) %>
      </p>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="medium-8 medium-offset-2 custom-container container">
      <table  class="full-width">
        <thead>
          <tr>
            <th><Activity>Exercises</Activity></th>
          </tr>
        </thead>
        <% @exercises.each do |exercise| %>
          <tr>
            <td>
              <div class="exercise-type"><%= exercise.activity %></div>
              <div class="exercise-intensity"><%= exercise.intensity %></div>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="submit-exercise">
    <p>Mark as completed:</p>
    <%= link_to fa_stacked_icon("check", base: 'star'), completeds_path(workout_id: @workout, workout_name: @workout.name), method: :post, class: 'submit-completed' %>
  </div>
<% end %>